### ISSUE TITLE
Add Test cases

### ISSUE THREAD

**Issue by rathorevaibhav** [avantifellows/plio-backend#184]
**Describe the task**
We have several functionalities in the backend that require test cases and increased code coverage.

The following breakdown describes components and possible test cases that can be written within.
1. Plio
   - [x] Plio CRUD
   - [x] Public plios are accessible by all
   - [x] Organization plios are visible to organization users only
   - [x] Personal plios are visible only to plio owners
   - [x] Plio duplicate functionality
   - [ ] User should not be able to update plio in another user's personal workspace
   - [ ] User should be able to update plio created by another user within the same org workspace
   - [ ] Plio visibility based on draft/publish status
2. Video
   - [x] Video CRUD
3. Item
   - [x] Item CRUD
   - [x] Item duplicate functionality
   - [ ] User should not be able to update another user's plio in the personal workspace with own item
   - [ ] User should not be able to update item created by another user in their personal workspace
   - [ ] User should be able to update another user's plio in the same org workspace with own item
   - [ ] User should be able to update item created by another user in the same org workspace
4. Question
   - [x] Question CRUD
   - [x] Question duplicate functionality
   - [ ] Subjective question related testing (character limit etc)
   - [ ] User should only be able to view own questions in personal workspace
   - [ ] User should not only be able to update questions in the personal workspace of another user
   - [ ] User should be able to view questions by all users in the same org workspace
   - [ ] User should be able to update questions created by any user in the same org workspace
5. Session
   - [ ] Session CRUD 
   - [ ] Retention array is correctly created for new session
   - [ ] Past session data gets copied over to a new session for the same user-plio combination
6. Session Answer
   - [ ] Session Answer CRUD
   - [ ] Answers from the past sessions get copied to a new session for the same user-plio combination
7.  Experiment
    - [ ] Experiment CRUD
8. Event
    - [ ] Event CRUD
9. Organization
    - [ ] Organanization CRUD
    - [ ] Only super user can create organizations
    - [ ] Normal users can see their organizations but not for other users
    - [ ] User not part of org should see authorization error when making a request with that org header
10. User
    - [x] OTP authentication
    - [ ] OTP should expire after configured time
    - [ ] Google based (convert token) Auth
    - [ ] User update config functionality
11. Organization User - Roles
    - [ ] Plio Super user can do all actions
    - [ ] Organization super-admin can perform CRUD only on org-admin and org-view users
    - [ ] Organization org-admin can perform CRUD only on org-view users
    - [ ] Org-view users cannot perform any CRUD operation for organization-user assignments
12. Image
    - [x] Image CRUD
    - [ ] File uploaded should be an image/GIF file, and not any other kind of file
    - [x] Images should be max 10 mb in size, if not, a proper response should be returned
    - [x] Duplicate image functionality
    - [ ] User should only be able to view own images in personal workspace
    - [ ] User should not be able to update images created by other users in their personal workspace
    - [ ] User should be able to view any image created by any user in the same org workspace
    - [ ] User should be able to update any image created by any user in the same org workspace

These can be worked on in small chunks every week to increase the code coverage. We can set weekly targets:
1. Week 1 - Target to reach 80%
2. Week 2 - Target to reach 85%
3. Week 3 - Target to reach 90%
4. Week 4 - Target to reach 95%

**Comment by NaveenGokavarapu19** [comment]
Hii i am new to opensource and i want to contribute to this issue. Can show me a example me sample test case so that i can understand and try writing test cases

**Comment by dalmia** [comment]
Hi @NaveenGokavarapu19. Thank you for your interest in contributing to the issue. However, this is an advanced issue and I would recommend that you choose a different open-source project to start your open-source journey.
